### ISSUE TITLE
No reader function for tag object when using cookie store

### ISSUE THREAD

**Issue by Heliosmaster** [weavejester/ring-oauth2#27]
If I have in my ring configuration

```(assoc-in site-defaults [:session :store] (cookie-store {:key "a very secret cookie key"}))```

I get the error:

```
java.lang.RuntimeException: No reader function for tag object
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:801)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:783)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:549)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
	at clojure.lang.EdnReader.read(EdnReader.java:145)
	at clojure.lang.EdnReader.read(EdnReader.java:111)
	at clojure.lang.EdnReader.readString(EdnReader.java:67)
	at clojure.edn$read_string.invokeStatic(edn.clj:46)
	at clojure.edn$read_string.invokeStatic(edn.clj:37)
	at clojure.edn$read_string.invoke(edn.clj:37)
	at ring.middleware.session.cookie$serialize.invokeStatic(cookie.clj:69)
	at ring.middleware.session.cookie$serialize.invoke(cookie.clj:68)
	at ring.middleware.session.cookie$seal.invokeStatic(cookie.clj:75)
	at ring.middleware.session.cookie$seal.invoke(cookie.clj:72)
	at ring.middleware.session.cookie.CookieStore.write_session(cookie.clj:91)
	at ring.middleware.session$bare_session_response.invokeStatic(session.clj:52)
	at ring.middleware.session$bare_session_response.invoke(session.clj:43)
	at ring.middleware.session$session_response.invokeStatic(session.clj:74)
	at ring.middleware.session$session_response.invoke(session.clj:66)
	at ring.middleware.session$wrap_session$fn__24588.invoke(session.clj:109)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__24630.invoke(keyword_params.clj:36)
	at ring.middleware.nested_params$wrap_nested_params$fn__24688.invoke(nested_params.clj:89)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__24986.invoke(multipart_params.clj:173)
	at ring.middleware.params$wrap_params$fn__25010.invoke(params.clj:67)
	at ring.middleware.cookies$wrap_cookies$fn__24467.invoke(cookies.clj:175)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__25116.invoke(absolute_redirects.clj:47)
	at ring.middleware.resource$wrap_resource$fn__25026.invoke(resource.clj:37)
	at ring.middleware.content_type$wrap_content_type$fn__25064.invoke(content_type.clj:34)
	at ring.middleware.default_charset$wrap_default_charset$fn__25088.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__17997.invoke(not_modified.clj:53)
	at ring.middleware.x_headers$wrap_x_header$fn__23471.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__23471.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__23471.invoke(x_headers.clj:22)
```

When reaching the step of the callback URI.

I suspect associng the `access-token` to the session is the culprit.

**Comment by weavejester** [comment]
It sounds like you've placed an object in your session that cannot be serialized. It seems unlikely the issue is the access token, as I wouldn't expect that to be an object.

Why don't you print out the session before it gets serialized, and see what data is causing the error?

**Comment by Heliosmaster** [comment]
I didn't place that object, `ring-oauth2` did: `expires_in` is a JodaTime which has no default EDN reader :-)

**Comment by Heliosmaster** [comment]
I've noticed that `clj-time 0.15.0` has added a `clj-time/date-time` tagged literal. And I've confirmed it works.

However, If I say
```                                       
(assoc-in [:session :store] (cookie-store {:key     (env :cookie-key)
                                                                      :readers clj-time.coerce/data-readers}))````

it still complains that `java.lang.RuntimeException: No reader function for tag clj-time/date-time`

**Comment by weavejester** [comment]
Thanks for looking into the issue. That `:expires` key does look like it's causing the issue. It should probably be converted to a `java.util.Date` to allow storage.

**Comment by Heliosmaster** [comment]
@weavejester I was also thinking that converting it to a `java.util.Date` would be better as it's better supported for storage, but then it would break compatibility with the current version. I made a PR which sort of solves this (one side of it at least, the other is in `cookie-store`). Do you think it's an okay solution?

**Comment by weavejester** [comment]
> I was also thinking that converting it to a `java.util.Date` would be better as it's better supported for storage, but then it would break compatibility with the current version.

What's stored in the session is entire internal, so we can change that however we want, as long as we keep the keys added to the request the same.

> I made a PR which sort of solves this (one side of it at least, the other is in `cookie-store`)

What do you mean "the other is in `cookie-store`"?

**Comment by Heliosmaster** [comment]
I manually put the `:readers` key in the cookie store initialization settings, albeit i don't think it's necessary

**Comment by weavejester** [comment]
I think converting it to a Date object might be generally more reliable. We can add something that converts to and from a date when we put it in the session store.

**Comment by amalantony** [comment]
@weavejester Is there a workaround for this problem I could use presently? Thanks!

**Comment by Jeiwan** [comment]
@amalantony If you're getting this error when using the Ring session middleware, you need to pass `{:readers *data-readers*}` to `cookie-store`, like `(cookie-store {:readers *data-readers*})`.

**Comment by jamiepratt** [comment]
@Jeiwan that might not be safe? Some of the readers in *data-readers* apparently use eval.

See comment here: https://clojuredocs.org/clojure.edn/read
